### ISSUE TITLE
Add YAML tag for "eval"

### ISSUE THREAD

**Issue by isaac-ped** [isaac-ped/Shremote#2]
e.g.:

```yaml
duration: 10
extra: 5
repetitions: 4

commands:
    prog:
        timing: $`{0.duration} + {0.extra}`
        arg: $" 'abc' * {0.repetitions}"
```

would expand to:
```yaml
commands:
    prog:
        timing: 15
        arg: 'abcabcabcabc'
```
Already done with "begin" and "duration" -- would just be a matter of adding a special tag for it
